name: c-i

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test Projects and Pipelines
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
          - x86_64
    permissions:
      contents: read
    runs-on: ubuntu-24.04-${{matrix.arch}}
    steps:
      - uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: chainguard-dev/actions/apt-faster@18e5e3427cf9d6bcfbefe60dca48e40292f000c5 # v1.5.13
      - uses: chainguard-dev/actions/setup-melange@18e5e3427cf9d6bcfbefe60dca48e40292f000c5 # v1.5.13
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: './go.work'
          cache-dependency-path: '**/*.sum'
      - name: Setup shellcheck
        uses: ./.github/actions/shellcheck
        with:
          version: v0.10.0
      - name: lint
        run: make lint
      - name: Build
        run: make build
      - name: Test all projects
        run: |
          make test-projects
      - name: Test in melange
        run: |
          make test-melange
      - name: Test pipeline validations
        run: |
          make test-pipelines
